apiVersion: v1
kind: Pod
metadata:
  name: multitool-test
  labels:
    app: multitool-test
spec:
  containers:
    - name: multitool
      image: wbitt/network-multitool
      command: ["sleep", "7200"]
