apiVersion: v1
kind: Service
metadata:
  name: service-backend
  labels:
    app: backend
    environment: dev
spec:
  selector:
    app: multitool-backend
  ports:
    - name: multitool
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
