---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hw
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/ubuntuk8/k8s-hw/data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-hw
  namespace: default
spec:
  volumeName: pv-hw
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-exchange-pvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-exchange-pvc
  template:
    metadata:
      labels:
        app: data-exchange-pvc
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            [
              "while true; do echo $(date) >> /shared/output-data.txt; sleep 5; done",
            ]
          volumeMounts:
            - name: pvol
              mountPath: /shared
        - name: multitool
          image: wbitt/network-multitool
          command: ["/bin/sh", "-c"]
          args: ["tail -f /shared/output-data.txt"]
          volumeMounts:
            - name: pvol
              mountPath: /shared
      volumes:
        - name: pvol
          persistentVolumeClaim:
            claimName: pvc-hw
